//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empired.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserId { get; set; }
        public string LoginName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<bool> IsStudent { get; set; }
        public Nullable<bool> IsTeacher { get; set; }
    }
}
